services:
    postgres_db:
        container_name: postgres_db
        image: postgres:15.2
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - postgres_db-data:/var/lib/postgresql/data
            - ./src/models/scripts/init:/docker-entrypoint-initdb.d
    redis_cache:
        container_name: redis_cache
        image: redis:7.0.11
        restart: always
        ports:
            - "6379:6379"
    node_server:
        container_name: node_server
        build: .
        env_file:
            - .env
        ports:
            - "3000:3000"
        depends_on:
            - postgres_db
            - redis_cache
volumes:
    postgres_db-data: {}
