CREATE TABLE IF NOT EXISTS passengers (
    carpool_id UUID NOT NULL,
    user_id UUID NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (carpool_id, user_id),
    FOREIGN KEY (carpool_id) REFERENCES carpools(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);